spring.application.name=albabot-backend
spring.datasource.url=jdbc:mysql://localhost:3306/albabot
spring.datasource.username=root
spring.datasource.password=youngvkf
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver